### ISSUE TITLE
deprecated methods

### ISSUE THREAD

**Issue by jokumo** [ambrosus/ambrosus-bridge-frontend#23]
![image](https://user-images.githubusercontent.com/16837904/166654319-81006c72-8b9e-4a1a-8b16-ab8dd5a805fd.png)

MetaMask: The event 'close' is deprecated and may be removed in the future. Please use 'disconnect' instead.
For more information, see: https://eips.ethereum.org/EIPS/eip-1193#disconnect

MetaMask: The event 'networkChanged' is deprecated and may be removed in the future. Use 'chainChanged' instead.
For more information, see: https://eips.ethereum.org/EIPS/eip-1193#chainchanged

MetaMask: 'ethereum.send(...)' is deprecated and may be removed in the future. Please use 'ethereum.sendAsync(...)' or 'ethereum.request(...)' instead. For more information, see: https://eips.ethereum.org/EIPS/eip-1193

**Comment by kishkoigor** [comment]
This warnings caused by [web3-react](https://github.com/NoahZinsmeister/web3-react) library.
We are using v6 of web3-react, as it stable, and according to [this issue](https://github.com/NoahZinsmeister/web3-react/issues/508), this warnings already fixed in beta v8 of web3-react. So we will upgrade web3-react to v8 as it will become stable.

Also, as stated in [this issue](https://github.com/MetaMask/metamask-extension/issues/9301#issuecomment-680955280), metamask team will not remove deprecated events and methods for the foreseeable future, so nothing to worry about

**Comment by jokumo** [comment]
Ok, thank you for your reply. I'll close this issue then...
